FROM debian:bookworm

RUN apt-get update && \
    apt-get upgrade && \
    apt-get install -y \
        cmake \
        make \
        g++ \
        git && \
    git clone https://github.com/google/googletest.git -b v1.14.0 && \
    cd googletest && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make && \
    make install

WORKDIR /web_serv
CMD make -C spec FSANITIZE=yes run