version: '3'

networks:
  web_serv:

volumes:
  web_serv:

services:
  web_serv:
    container_name: web_serv
    image: web_serv
    build:
      context: .
    networks:
      - web_serv
    ports:
      - "80:80"
    volumes:
      - web_serv:/web_serv
    restart: unless-stopped

  test:
    container_name: test
    image: test
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - web_serv
    volumes:
      - web_serv:/web_serv
    depends_on:
      - web_serv
