version: '3'

networks:
  web_serv:

volumes:
  src_cache:

services:
  web_serv:
    container_name: web_serv
    image: web_serv
    build:
      context: .
    networks:
      - web_serv
    volumes:
      - src_cache:/web_serv/obj
    ports:
      - "8080:8080"
    restart: unless-stopped

  # test:
  #   container_name: test
  #   image: test
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.test
  #   networks:
  #     - web_serv
  #   volumes:
  #     - type: bind
  #       source: .
  #       target: /web_serv
  #   depends_on:
  #     - web_serv

  # nginx:
  #   container_name: nginx
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.nginx
  #   image: mynginx
  #   volumes:
  #     - type: bind
  #       source: www
  #       target: /usr/share/nginx/html
  #   ports:
  #     - "8080:8080"
  #   restart: on-failure
