FROM debian:bookworm

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
        cmake \
        make \
        g++ \
        git && \
    git clone https://github.com/google/googletest.git -b v1.14.0 && \
    cd googletest && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make && \
    make install

VOLUME /web_serv
WORKDIR /web_serv/spec
CMD make FSANITIZE=yes && ./debug.out --gtest_filter=-Example* && tail -f /dev/null
# CMD tail -f /dev/null