name: inspect

services:
  nginx:
    container_name: nginx
    build:
      context: ./
    image: mynginx
    volumes:
      - html:/usr/share/nginx/html
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  html:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./www
